using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.NetworkInformation;
using System.Text;
using System.Threading.Tasks;

namespace FMS_NouraAlmaskari_.Models
{
    public class Flight
    {
        public int flightId { get; set; } // Unique identifier for each scheduled flight
        public string flightCode { get; set; } // Airline flight code (e.g. OA-201) — generated by system
        public int aircraftId { get; set; } // ID of the aircraft assigned to this flight
        public int pilotId { get; set; } // ID of the pilot assigned to this flight
        public string origin { get; set; } // Departure airport / city
        public string destination { get; set; } // Arrival airport / city
        public string departureDate { get; set; } // Scheduled departure date
        public string departureTime { get; set; } // Scheduled departure time
        public int duration { get; set; }
        public decimal ticketPrice { get; set; } // Price per seat for this flight
        public int availableSeats { get; set; } // Number of seats still open for booking — decrements on booking
        public string status{ get; set; } // Flight status: Scheduled | Departed | Cancelled

        public Flight(int flightId, string flightCode, int aircraftId, int pilotId, string origin, string destination, string departureDate, string departureTime, int duration, decimal ticketPrice, int availableSeats, string status)
        {
            this.flightId = flightId;
            this.flightCode = flightCode;
            this.aircraftId = aircraftId;
            this.pilotId = pilotId;
            this.origin = origin;
            this.destination = destination;
            this.departureDate = departureDate;
            this.departureTime = departureTime;
            this.duration = duration;
            this.ticketPrice = ticketPrice;
            this.availableSeats = availableSeats;
            this.status = status;
        }
        
        public void printInfo()
        {
            Console.WriteLine($"Flight ID: {flightId} | Flight Code: {flightCode} | Aircraft ID: {aircraftId} " +
                $"Pilot ID: {pilotId} | Origin: {origin} | Destination: {destination}" +
                $"Departure Date: {departureDate} | Departure Time: {departureTime} | Ticket Price: {ticketPrice}" +
                $"AvailableSeats: {availableSeats} | Status: {status} | Duration: {duration}");
        }
    }
}
